# Brock Huskisson
## Week 10 10/29/20
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [2]:
print("Hello world")

Hello world


In [3]:
my_list = [11,22,33,44,55,66,77]

print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [4]:
my_arr = np.array(my_list)

In [5]:
print(my_arr.dtype)

int32


In [6]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']

my_strArr = np.array(fruits)

In [7]:
print(my_strArr.dtype)

<U6


In [9]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')


In [10]:
print(my_arr2.dtype)

|S2


In [13]:
my_arr2 = np.array([1,2,3,4,5], dtype='S')
                   
print(my_arr2.dtype)


|S1


In [15]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

In [16]:
print(my_arr3.dtype)

int32


In [26]:
my_arr4 = np.array(['1','2','3','4','5'], dtype='i8')

In [27]:
print(my_arr4)
print(my_arr4.dtype)

[1 2 3 4 5]
int64


In [24]:
my_error = np.array(['1','2','c','4','5'], dtype='i')

ValueError: invalid literal for int() with base 10: 'c'

In [28]:
scores = [78.5,88.9,90.3,89.9]

my_arr4 = np.array(scores)

In [29]:
print(my_arr4)

[78.5 88.9 90.3 89.9]


In [30]:
arr = my_arr4.astype('i')

In [31]:
print(arr)

[78 88 90 89]


In [32]:
arr = np.array([1,0,0,3,4,5,6,7,0])

In [33]:
print(arr.dtype)

int32


In [39]:
bool_arr = arr.astype(bool)

In [40]:
print(arr)
print(bool_arr)

[1 0 0 3 4 5 6 7 0]
[ True False False  True  True  True  True  True False]


In [60]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)


[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [61]:
#nunpy built-in functions to generate arrays from existing arrays
# copy and view, instead of using =
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [62]:
arr[3] = 4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [63]:
#view 
my_list = [11,12,13,14,15]

arr = np.array(my_list)
v_arr = arr.view()

print(arr)
print(v_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [64]:
arr[3] = 4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [65]:
v_arr[2] = 3
print(arr)
print(c_arr)

[11 12  3  4 15]
[11 12 13 14 15]


In [66]:
print(c_arr.base)
print(v_arr.base)

None
[11 12  3  4 15]


In [69]:
#shape gives the number of elemetns in each dimension
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
print(my_arr.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)


In [70]:
# shape return 2 dimensions and each dimension has 5 elements

In [72]:
arr = np.array(lst1, ndmin=4)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [73]:
arr = np.array(lst1, ndmin=6)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [74]:
# each inde in the shape tells the number of elements in that dimension