# Brock Huskisson
## Week 11 11/03/2020
### Python numpy creating, processing, transporting arrays

In [1]:
import numpy as np

arr_2d = np.array([[1,2,3,4], [5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [2]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print(arr.ndim)
print(arr.dtype)

1
float64


In [4]:
arr_2d = np.zeros((5,5))

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
float64


In [5]:
arr = np.ones((5,5))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [6]:
arr = np.empty((3,3), dtype=int)

print(arr)
print(arr.ndim)
print(arr.dtype)

[[7602286 7077989 3407926]
 [4587552 7143521 7077993]
 [2097273 2097206 7274573]]
2
int32


In [7]:
arr = np.empty((6,6), dtype=int)

print(arr)
print(arr.ndim)
print(arr.dtype)

[[4128860 6029375 3801155 5570652 6619251 7536754]
 [6357084 6553710 6488161 7209071 6357092 3014748]
 [7340137 7602297 7274600 6029422 7471216 6684783]
 [7077993 6226021 6619236 6357094 7078005 6029428]
 [6881384 7602291 7471215 3014777 7405683 6881388]
 [6619252 6946861 7667823 7209074 7077985       0]]
2
int32


In [8]:
#arrange 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
arr = np.arange(10,100,5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)
1
int32


In [11]:
arr = np.arange(1,13,1)
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [12]:
#reshape arrays 1-D to 2-D
arr_2d = arr.reshape(3,4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
arr_2d = arr.reshape(4,3)

print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
arr_2d = arr.reshape(6,2)

print(arr_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [15]:
arr_2d = arr.reshape(1,12)

print(arr_2d)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [16]:
arr_2d = arr.reshape(12,1)

print(arr_2d)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [17]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(3,2,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [18]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(6,1,2)
print(arr_3d)

[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]


In [19]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(1,6,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(1,2,6)
print(arr_3d)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]


In [21]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(2,2,3)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(2,6,1)
print(arr_3d)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [23]:
#reshape 1-D to 3-D
arr_3d = arr.reshape(2,1,6)
print(arr_3d)

[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]


In [25]:
#arr_2d = arr.reshape(5,3)

In [26]:
#reshape is a view or copy
print(arr_2d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
arr_3d = arr.reshape(2,2,-1)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
#iterating 1-D 
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [31]:
#iterating 2-D
arr = np.array([[1,2,3,4], [5,6,7,8]])

for n in arr:
    for x in n:
            print(x)

1
2
3
4
5
6
7
8


In [32]:
#iterating 3-D arrays
arr_3d = np.array([[[1,2,3], [4,5,6]] ,[[7,8,9], [10,11,12]]])
print(arr_3d)
print(arr_3d.shape)
print(arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3


In [33]:
for n in arr_3d:
    for x in n:
        for i in x:
            print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
#nditer iterates on each scalar element in the np array 
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
arr_2d.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr_2d[:,::2]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [37]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
for idx, n in np.ndenumerate(arr):
    print(idx, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [40]:
arr_2d = np.array([[1,2],[3,4], [5,6], [7,8]])
print(arr_2d.shape)

(4, 2)


In [41]:
for i, v in np.ndenumerate(arr_2d):
    print(i, v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [42]:
arr_2d * arr_2d

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [43]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [44]:
arr_2d**3

array([[  1,   8],
       [ 27,  64],
       [125, 216],
       [343, 512]], dtype=int32)

In [45]:
1 / arr_2d

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ]])

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [48]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
arr[::3]

array([ 1,  4,  7, 10])

In [50]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr[0:6] = 100

In [53]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [54]:
import numpy as no

arr_2d = np.array([[5,10,25],[15,10,20], [20,30,25]])

print(arr_2d.shape)
print(arr_2d)

(3, 3)
[[ 5 10 25]
 [15 10 20]
 [20 30 25]]


In [55]:
arr_2d[1]

array([15, 10, 20])

In [56]:
arr_2d[1,0]

15

In [58]:
#slicing
arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [60]:
arr_2d[1:, :2]

array([[15, 10],
       [20, 30]])

In [61]:
arr_2d[2]

array([20, 30, 25])

In [62]:
arr_2d[2,-1]

25

In [63]:
arr = np.zeros((8,9))

In [64]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
arr.shape

(8, 9)

In [67]:
arr.shape[0]

8

In [68]:
arr.shape[1]

9

In [69]:
arr.shape[2]

IndexError: tuple index out of range

In [70]:
l = arr.shape[0]

for idx in range(l):
    arr[idx] = 10
    
arr

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [71]:
for idx in range(l):
    arr[idx] = idx*2
    
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [72]:
arr[1:7]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [73]:
arr[1:7, 3:6]

array([[ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.],
       [12., 12., 12.]])

In [79]:
arr[::2,3:6]

array([[ 0.,  0.,  0.],
       [ 4.,  4.,  4.],
       [ 8.,  8.,  8.],
       [12., 12., 12.]])

In [80]:
#fancy indexing
arr[[1,6,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [81]:
arr[[3, 5]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [90]:
#reshape

arr = np.arange(45).reshape(9,5)

#output
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [91]:
arr_t = arr.T

#output
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [92]:
np.dot(arr_t,arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [93]:
arr_3d = np.arange(45).reshape(3,5,3)

arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [94]:
# swapaxes
arr = np.array([[1,2,3]])

arr

array([[1, 2, 3]])

In [95]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])