# Brock Huskisson
# Week 11 - 11/05/20
### Python Numpy Universal Functions

In [6]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]
z=[]


for i, j in zip (arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [8]:
#zip

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [9]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [11]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [28]:
arr1 = np.random.randn(10)

In [29]:
arr1

array([-1.07459724, -0.92608146,  1.40841919, -2.41621074, -1.51995717,
       -1.20089718, -0.02113844, -0.45138646,  0.05826444,  0.85789901])

In [30]:
arr2 = np.random.randn(10)

In [31]:
arr

array([ 0.58695604, -0.19259197,  1.41702459, -0.83629553,  0.71812718,
        1.18704516,  0.30000382,  1.43414241, -1.26162193,  0.48277481])

In [32]:
np.add(arr1,arr2)

array([-0.27247703, -0.86402671,  0.37278738, -1.82176891, -0.79246773,
       -1.4433027 ,  1.58475004, -0.01069879,  0.11273412, -0.95693231])

In [33]:
np.maximum(arr1,arr2)

array([ 0.80212021,  0.06205475,  1.40841919,  0.59444182,  0.72748943,
       -0.24240552,  1.60588848,  0.44068767,  0.05826444,  0.85789901])

In [35]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [38]:
np.where(arr < 4, -1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [39]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [46]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, True, True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2, arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [44]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2, arr_b)]

arr3

[1, 20, 3, 4, 50]

In [48]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])