# Brock Huskisson
# Week 11 - 11/05/20
### Python Numpy Universal Functions

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]
z=[]


for i, j in zip (arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [2]:
#zip

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
arr1 = np.random.randn(10)

In [7]:
arr1

array([-0.01749631,  0.18336486, -1.02099625, -0.35853639,  0.06930249,
       -1.64642829,  0.43886468, -0.2275748 , -0.44774995,  0.99707142])

In [8]:
arr2 = np.random.randn(10)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
np.add(arr1,arr2)

array([ 1.23951453,  1.10461265, -0.78836554, -1.32609295,  0.38288484,
       -2.45392848, -1.00837257, -0.58614421,  1.37102139,  0.2465693 ])

In [11]:
np.maximum(arr1,arr2)

array([ 1.25701083,  0.92124779,  0.2326307 , -0.35853639,  0.31358236,
       -0.80750019,  0.43886468, -0.2275748 ,  1.81877134,  0.99707142])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
np.where(arr < 4, -1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [15]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, True, True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2, arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2, arr_b)]

arr3

[1, 20, 3, 4, 50]

In [18]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [20]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6], [7,8]])
cond = np.array([[True, False], [True, True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [21]:
np.where([[True, False], [True, True]], [[5,6], [7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [24]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 0.86889336,  0.35923861, -1.67720583],
       [ 0.10830274,  0.75356485, -0.01475474],
       [-1.71121955, -0.98083028, -1.79972538]])

In [27]:
np.where(arr<0, 0, arr)

array([[0.86889336, 0.35923861, 0.        ],
       [0.10830274, 0.75356485, 0.        ],
       [0.        , 0.        , 0.        ]])

In [28]:
arr_b = np.array([True, False, True, False, False])

arr_b.any()

True

In [29]:
arr_b.all()

False

In [30]:
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Ornage', 'Cherry', 'Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Ornage'], dtype='<U6')

In [33]:
np.in1d(['Apple', 'Cherry', 'Grape'],fruits)

array([ True,  True, False])

In [35]:
#Statistical measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
arr.sum()

45

In [37]:
arr.sum(0)

array([12, 15, 18])

In [38]:
arr.sum(1)

array([ 6, 15, 24])

In [39]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [40]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [41]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [42]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [43]:
arr.mean()

5.0

In [44]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [45]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [47]:
np.mean(arr,axis=0)


array([4., 5., 6.])

In [48]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [49]:
arr.var()

6.666666666666667

In [51]:
arr.std()

2.581988897471611

In [52]:
arr = np.array([3,5,74,6,8,9,9,3,2,14,11,16,23,63])
arr.sort()

arr

array([ 2,  3,  3,  5,  6,  8,  9,  9, 11, 14, 16, 23, 63, 74])

In [53]:
#identity array
i = np.eye(5)

i 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [57]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)

a * i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [58]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [59]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [61]:
#Transpose

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)
print(arr)
print('--------------------')

t = arr.T

print(t)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [62]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [63]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [65]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
arr_3d = np.arange(20).reshape((2,5,2))
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [70]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [71]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [72]:
np.random.random((4,4))

array([[0.04436601, 0.85658731, 0.8415641 , 0.09437246],
       [0.92669443, 0.2795917 , 0.65382836, 0.03859864],
       [0.13106273, 0.64506211, 0.01999967, 0.02064697],
       [0.20747547, 0.30154854, 0.7797578 , 0.45803433]])

In [73]:
from numpy.random import random 
random((4,4))

array([[0.05361344, 0.65727194, 0.71634414, 0.66017775],
       [0.08518404, 0.95522542, 0.83702541, 0.16786009],
       [0.5119578 , 0.28016802, 0.52595159, 0.32922055],
       [0.88468125, 0.96549178, 0.69480392, 0.88729899]])

In [74]:
from numpy.random import randn
randn(5,5)

array([[ 0.16390831,  0.77451481,  0.65082232,  1.15489706,  1.05193482],
       [-0.0164471 , -0.5125365 ,  0.60204209, -1.8534163 ,  1.06480626],
       [ 3.20663362, -0.37020828, -1.45912623,  0.29339624, -1.84733233],
       [-1.93456575, -0.08766152, -1.51018841, -1.21722763,  0.75032865],
       [-0.13890344,  0.63537706,  0.39345917,  0.55351499,  0.35212267]])

In [75]:
randn(5)

array([-0.52332496, -0.29730774, -1.82185811,  1.83763223,  0.3727994 ])

In [76]:
np.random.randint(10,50)

18

In [78]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [79]:
import pandas as pd